main: joni.wildrtp.WildRTP
name: WildRTP
version: 2.0
author: LasaJoni
api-version: 1.17
description: With the help of the WildRTP, you can use a command to teleport to a random location.
commands:
  wild:
    description: Random Teleport
    aliases: [wilderness, rtp, randomtp, randomteleport, wildtp]
permissions:
  wildrtp.rtp:
    description: "RTP"
    default: true
  wildrtp.cooldown.bypass:
    description: "Bypass the cooldown, if enabled"
    default: op
  wildrtp.cooldown.custom:
    description: "Set a custom cooldown under the section custom in the config.yml"
  wildrtp.movetimer.bypass:
    description: "Bypass the movetimer, if enabled"
    default: op
  wildrtp.reload:
    description: "Reload the config"
    default: op
