# Config for WildRTP
# cooldown in ms
# When permission.teleport: "NONE", no permission is set for the teleport
teleport:
  max-x: 2500
  max-z: 2500
  min-x: 0
  min-z: 0
  cooldown: 0

permission:
  teleport: "NONE"
  bypass-cooldown: "wildrtp.bypass"
  reload: "wildrtp.reload"

plugin-settings:
  prefix: "[§2WildRTP§f] §6"

disabled-worlds:
  #example_world_name: "example_world_name"
  #world_the_end: "world_the_end"

# Advanced
# Do not touch unless you know what are doing
config-version: 1.2
